allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d15c0de0-0000-4000-8000-000000000023:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3e5e6fe0-a2f7-447d-9c83-eefda145cc39 # Vorname
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-00000000001c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ff374c99-3671-42e2-b498-135cfb4390df # Nachname
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-00000000001d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8764757-fd97-4cf4-952b-ea5023c38b4e # Funktion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-00000000001e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe1e327f-f713-41a4-8ed3-eaac7c941b7b # Bild
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-00000000001f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c284b6a7-ad21-48f7-899c-c0a35b3fd207 # Email
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-000000000020
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 94611176-dc23-4b3b-b517-57ef2d20385c # Phone
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-000000000021
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: d15c0de0-0000-4000-8000-000000000022
        userCondition: null
    thumbFieldKey: null
handle: person
hasTitleField: false
icon: user
name: Teammitglied
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{firstName} {lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
