allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d15c0de0-0000-4000-8000-000000000069:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d15c0de0-0000-4000-8000-000000000063
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f1cd7cb0-48a1-4e28-81f5-a40fd957819c # Akkordeons
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15c0de0-0000-4000-8000-000000000064
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d15c0de0-0000-4000-8000-000000000068
        userCondition: null
    thumbFieldKey: null
handle: sectionAccordions
hasTitleField: true
icon: bars
name: 'Sektion Akkordeons'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
