allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  cb44a01e-bb54-466f-ad59-810c05362ef6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fb1763f4-a5c8-4050-86ae-eccae872d18c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f5a06c4-2f53-48c0-9dc7-e5dd75b0033f # FAQs
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5366d64c-2bb3-4471-8ec8-9f2864df13bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c84c691c-6219-41f3-91d7-55da471519ba # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd89bab3-effb-4d73-855e-db91caa42518
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e70197fa-25d7-47d9-92fc-4c89ee7a7639
        userCondition: null
    thumbFieldKey: null
handle: sectionFaqs
hasTitleField: true
icon: bars
name: 'Sektion FAQs'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
