columnSuffix: null
handle: collection
instructions: 'Wähle die Übersicht, die auf dieser Seite angezeigt wird.'
name: Übersicht
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4c12bdf9-f8b7-4605-8d4b-eb70638cd78e # Newsübersicht
        -
          - group
          - Übersichten
    -
      __assoc__:
        -
          - uid
          - f03d9339-25b4-4528-bb59-e2371e28f748 # Projektübersicht
        -
          - group
          - Übersichten
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
