columnSuffix: null
handle: email
instructions: null
name: E-Mail
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: false
  placeholder: info@steibock-ag.ch
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
