columnSuffix: null
handle: heroTitle
instructions: 'Use <b>...</b> for bold text. Add a new line for each title line.'
name: 'Hero title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
