columnSuffix: null
handle: orderBy
instructions: null
name: Sortierung
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Datum: neueste zuerst'
        -
          - value
          - newest
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - 'Datum: älteste zuerst'
        -
          - value
          - oldest
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - 'Alphabetisch A–Z'
        -
          - value
          - titleAsc
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - 'Alphabetisch Z–A'
        -
          - value
          - titleDesc
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Craft-Reihenfolge
        -
          - value
          - manual
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
