columnSuffix: null
handle: showCategoryFilters
instructions: null
name: 'Kategorie-Filter anzeigen'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
