isPublic: false
name: NextJs
scope:
  - 'sites.1f9dcaf3-3f9d-4e81-996d-7bb1aefe81c8:read' # Ubiq Next
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.2ff02e44-9d61-41bd-bf2c-5d7434a838d2:read' # Navigations
  - 'sections.bbe74a36-5c8c-4b60-8191-579ce8df7265:read' # News
  - 'sections.7ee4a1a7-4145-4182-aa07-5fa4c0b1f501:read' # Jobs
  - 'sections.4f2778cd-2c58-49b8-b0df-556a94f851df:read' # Projekte
  - 'sections.a21f242e-e528-4422-bda4-cd4f181b891c:read' # Team
  - 'sections.60b20bac-64e8-4103-8fbb-afa9a4cfacf7:read' # Seiten
  - 'sections.0e026e73-9c8a-42a9-8750-396dc0f8f17a:read' # Wiederverwendbare Abschnitte
  - 'nestedentryfields.7de1aa36-fe1f-4d28-b98e-4d1e7123d0e9:read' # Rich Text
  - 'nestedentryfields.6f4fd0ee-dca6-41bc-9a7d-a027e3e1077f:read' # Links
  - 'nestedentryfields.30d1b8b2-bc92-4f54-a3fe-b915f5a0ce9d:read' # Navigation Items
  - 'nestedentryfields.59bffd50-bf6c-4c93-851a-4bf659e49ffa:read' # Children
  - 'nestedentryfields.360652e6-00ff-4774-b5c7-d9ad1331e09b:read' # Abschnitte
  - 'nestedentryfields.abdba094-401c-4d18-a918-e8d2e40dbdc9:read' # Übersicht
  - 'nestedentryfields.f1cd7cb0-48a1-4e28-81f5-a40fd957819c:read' # Akkordeons
  - 'nestedentryfields.7b8cb926-d9d1-4d32-8cc7-831203fb3017:read' # Lösungen
  - 'nestedentryfields.5f5a06c4-2f53-48c0-9dc7-e5dd75b0033f:read' # FAQs
  - 'nestedentryfields.1b0314f0-f88d-4847-b954-dad1fa12cb2f:read' # Downloads
  - 'nestedentryfields.92bae2f9-15a0-4712-a3df-69a3d0357913:read' # Social Links
  - 'volumes.f9f4c0c9-6e35-42b7-91b6-232b6b0068a4:read' # Uploads
  - 'globalsets.691eebac-34af-4bd3-bbd9-eac59b884edb:read' # Footer
  - 'globalsets.0c783779-c106-449f-b292-e9dbd9f195e4:read' # Legal
  - 'globalsets.56cd8fce-1035-4c04-9a6b-05704a65ca51:read' # SEO
  - 'globalsets.6376b934-148c-462e-a7b6-d8d6877bacdc:read' # Error Page
  - 'categorygroups.ef3c57ff-b698-4a91-a2f2-b33e88127d85:read' # News
  - 'categorygroups.6db66595-1c9d-4510-9dba-d8004ddc9a0a:read' # Lösungen
  - 'categorygroups.2aa06d63-0d01-4d4e-b6a3-1b60edc7b101:read' # Job-Kategorien
  - 'freeformForms.all:read'
  - 'freeformForms.464b5690-3349-4956-a97c-f9d0ecc73d2e:read'
  - 'freeformSubmissions.all:create'
  - 'freeformSubmissions.464b5690-3349-4956-a97c-f9d0ecc73d2e:create'
  - 'directive:transform'
